server:
  port: 8085


spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aryan1234-coder/microservices-configuration
          clone-on-start: true
